sudo: false
language: node_js
node_js:
  - "0.10"
before_install: 
  - npm install -g gulp
  - npm install -g bower
install: 
  - npm install
  - bower install
before_script: gulp
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c9580f9ca6eea728628a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
